# 应用配置
app:
  name: "fastgox-tcp-game-server"
  version: "1.0.0"
  env: "dev"
  host: "0.0.0.0"
  port: 3250
  debug: true

# 数据库配置 - PostgreSQL
database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "gamedb"
  sslmode: "disable"
  timezone: "Asia/Shanghai"
  max_open_conns: 100
  max_idle_conns: 10
  log_level: "info"

# JWT配置
jwt:
  secret_key: "your-secret-key-here"