# 应用配置
app:
  name: "fastgox-api-starter API"
  version: "1.0.0"
  env: "dev"
  port: 8080
  debug: true
  swagger:
    host: "/" # 为空时自动生成 localhost:8080
    scheme: "http" # 开发环境使用 http
    base_path: "/goapi/v1"

# 数据库配置 - MySQL
database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  user: "root"
  password: "password"
  dbname: "fastgox-api-starter"
  sslmode: "disable"
  timezone: "Asia/Shanghai"
  max_open_conns: 100
  max_idle_conns: 10
  log_level: "info"

# JWT配置
jwt:
  secret_key: "your-secret-key-here"
