basePath: /api/v1
info:
  contact: {}
  description: fastgox-api-starter AI聊天服务API
  title: fastgox-api-starter API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
